name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(dd/MM/yyyy)"
      report_date_end:
        description: "Report date end(dd/MM/yyyy)"

permissions:
  contents: read
  pull-requests: read
  issues: read
  
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
            ##  In the case of a personal access token, it needs to be added to the repository's secrets and 
            ##  used in this field.
            GITHUB_TOKEN:             ${{ secrets.REPORT_TOKEN }} 

            # Make sure to specify the name of the repository where the issue will be created
            GITHUB_REPO_FOR_ISSUE:    project_testing_developer_report 

            # Make sure to specify the owner of the repository where the issue will be created
            GITHUB_OWNER_FOR_ISSUE:   xhrist14n 

            # Be sure to list the owner and repository name in the format owner/repo
            GITHUB_OWNERS_REPOS:      xhrist14n/project_testing_developer_report 

            CORE_HOURS_START:         "8:00"
            CORE_HOURS_END:           "18:00"

            TIMEZONE:                 "America/Lima"
            
            SHOW_CORRELATION_GRAPHS:   true
            SHOW_ACTIVITY_TIME_GRAPHS: true
            
            REPORT_DATE_START:        ${{ inputs.report_date_start }}
            REPORT_DATE_END:          ${{ inputs.report_date_end }}

            USE_CHARTS:               true       

            SHOW_STATS_TYPES:         "timeline, workload, pr-quality, code-review-engagement, response-time"
            APPROVAL_TIME_INTERVALS:  '1=fast,3=medium,5=slow'
            TOP_LIST_AMOUNT:          100
            REPORT_PERIOD:            hours
            
